apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
        - name: backend
          image: umgtato/bpoke:v3
          env:
          - name: T_S 
            value: 2b6cf03b7d7b80f97f0bf676692c19
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-backend
spec:
  type: ClusterIP
  selector:
    app: backend-deployment
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poke
spec:
  selector:
    matchLabels:
      app: poke
  replicas: 1
  template:
    metadata:
      labels:
        app: poke
    spec:
      containers:
      - name: frontend
        image: umgtato/front-pokedex:v3
        env:
          - name: REACT_APP_URLBACK 
            value: svc-backend
---
apiVersion: v1
kind: Service
metadata:
  name: poke-server
spec:
  type: LoadBalancer
  selector:
    app: poke
  ports:
    - port: 80
      targetPort: 3000