version: "1"
services: 
 react-app: 
   build: 
     context: ./front 
   image: umgtato/front-pokedex
   environment:
      REACT_APP_URLBACK: http://172.26.24.71:8000
   ports: 
     - "3000:3000"
   stdin_open: true